[RSDungeonsConfig]
addDungeonsToModdedBiomes = true
blacklistedDungeonBiomes = ""

[RSDungeonsConfig.attemptsPerChunk]
badlandsDungeonAttemptsPerChunk = 8
darkForestDungeonAttemptsPerChunk = 8
desertDungeonAttemptsPerChunk = 8
jungleDungeonAttemptsPerChunk = 8
mushroomDungeonAttemptsPerChunk = 8
snowDungeonAttemptsPerChunk = 8
icyDungeonAttemptsPerChunk = 8
swampDungeonAttemptsPerChunk = 8
endDungeonAttemptsPerChunk = 0
netherDungeonAttemptsPerChunk = 0
oceanDungeonAttemptsPerChunk = 5

[RSDungeonsConfig.minHeight]
badlandsDungeonMinHeight = 2
darkForestDungeonMinHeight = 2
desertDungeonMinHeight = 2
jungleDungeonMinHeight = 2
mushroomDungeonMinHeight = 2
snowDungeonMinHeight = 2
icyDungeonMinHeight = 2
swampDungeonMinHeight = 2
endDungeonMinHeight = 2
netherDungeonMinHeight = 2
oceanDungeonMinHeight = 3

[RSDungeonsConfig.maxHeight]
badlandsDungeonMaxHeight = 255
darkForestDungeonMaxHeight = 255
desertDungeonMaxHeight = 255
jungleDungeonMaxHeight = 255
mushroomDungeonMaxHeight = 255
snowDungeonMaxHeight = 255
icyDungeonMaxHeight = 255
swampDungeonMaxHeight = 255
endDungeonMaxHeight = 255
netherDungeonMaxHeight = 255
oceanDungeonMaxHeight = 255
[RSMainConfig]
blacklistedDimensions = "the_bumblezone:the_bumblezone,the_aether:the_aether"
importModdedItems = true
blacklistedRSLoottablesFromImportingModdedItems = ""

[RSMainConfig.misc]
addBoulderToModdedBiomes = false
blacklistedBoulderBiomes = ""
boulderTiny = true
boulderGiant = true
diamondChanceInGiantBoulders = 7000
giantBouldersPerChunk = 0.25

[RSMainConfig.jungleFortress]
jungleFortressMaxChunkDistance = 98
addJungleFortressToModdedBiomes = true
blacklistedFortressBiomes = ""
silverfishSpawnrate = 0.5
lootChests = true

[RSMainConfig.igloos]
blacklistedIglooBiomes = ""
grassyIglooMaxChunkDistance = 41
addGrassyIglooToModdedBiomes = true
stoneIglooMaxChunkDistance = 41
addStoneIglooToModdedBiomes = true

[RSMainConfig.ruinedPortals]
blacklistedRuinedPortalsBiomes = ""
addRuinedPortalEndToModdedBiomes = true
ruinedPortalEndMaxChunkDistance = 57

[RSMainConfig.ruins]
blacklistedRuinsBiomes = ""
addRuinsNetherToModdedBiomes = true
ruinsNetherMaxChunkDistance = 35

[RSMainConfig.cities]
blacklistedCitiesBiomes = ""
addCityNetherToModdedBiomes = false
cityNetherMaxChunkDistance = 1001
[RSTemplesConfig.temples]
blacklistedTempleBiomes = ""
netherWastelandTempleMaxChunkDistance = 27
addNetherWastelandTempleToModdedBiomes = false
netherBasaltTempleMaxChunkDistance = 27
addNetherBasaltTempleToModdedBiomes = false
netherCrimsonTempleMaxChunkDistance = 1001
addNetherCrimsonTempleToModdedBiomes = false
netherWarpedTempleMaxChunkDistance = 1001
addNetherWarpedTempleToModdedBiomes = false
netherSoulTempleMaxChunkDistance = 1001
addNetherSoulTempleToModdedBiomes = false
[RSTemplesConfig.pyramids]
blacklistedPyramidBiomes = ""
netherPyramidMaxChunkDistance = 1001
addNetherPyramidToModdedBiomes = false
badlandsPyramidMaxChunkDistance = 37
addBadlandsPyramidToModdedBiomes = true
pyramidSnowyMaxChunkDistance = 1001
addPyramidSnowyToModdedBiomes = false
pyramidEndMaxChunkDistance = 1001
addPyramidEndToModdedBiomes = false
pyramidIcyMaxChunkDistance = 1001
addPyramidIcyToModdedBiomes = false
[RSMineshaftsConfig]
lootChestsMS = true
addMineshaftsToModdedBiomes = true
blacklistedMineshaftBiomes = "betterend:sulphur_springs"

[RSMineshaftsConfig.spawnrate]
birchMineshaftSpawnrate = 40
jungleMineshaftSpawnrate = 40
desertMineshaftSpawnrate = 0
stoneMineshaftSpawnrate = 0
savannaMineshaftSpawnrate = 40
icyMineshaftSpawnrate = 0
oceanMineshaftSpawnrate = 0
taigaMineshaftSpawnrate = 40
swampAndDarkForestMineshaftSpawnrate = 40
endMineshaftSpawnrate = 0
netherMineshaftSpawnrate = 0
crimsonMineshaftSpawnrate = 0
warpedMineshaftSpawnrate = 0

[RSMineshaftsConfig.minHeight]
birchMineshaftMinHeight = 8
jungleMineshaftMinHeight = 8
desertMineshaftMinHeight = 8
stoneMineshaftMinHeight = 8
savannaMineshaftMinHeight = 8
icyMineshaftMinHeight = 8
oceanMineshaftMinHeight = 8
taigaMineshaftMinHeight = 8
swampAndDarkForestMineshaftMinHeight = 8
endMineshaftMinHeight = 30
netherMineshaftMinHeight = 8
crimsonMineshaftMinHeight = 8
warpedMineshaftMinHeight = 8

[RSMineshaftsConfig.maxHeight]
birchMineshaftMaxHeight = 45
jungleMineshaftMaxHeight = 45
desertMineshaftMaxHeight = 45
stoneMineshaftMaxHeight = 45
savannaMineshaftMaxHeight = 45
icyMineshaftMaxHeight = 45
oceanMineshaftMaxHeight = 25
taigaMineshaftMaxHeight = 45
swampAndDarkForestMineshaftMaxHeight = 45
endMineshaftMaxHeight = 37
netherMineshaftMaxHeight = 13
crimsonMineshaftMaxHeight = 13
warpedMineshaftMaxHeight = 13

[RSMineshaftsConfig.misc]
barrensIslandsEndMineshafts = false
[RSStrongholdsConfig]
strongholdSizeSH = 100.0
allowExtraSpawnersSH = false
lootChestsSH = true
turnOffVanillaStrongholds = false
blacklistedStrongholdBiomes = ""

[RSStrongholdsConfig.stonebrick]
allowStonebrickStrongholdToVanillaBiomes = false
addStonebrickStrongholdToModdedBiomes = false
silverfishSpawnrateSH = 0.8
stonebrickStrongholdMinHeight = 0
stonebrickStrongholdMaxHeight = 45
stonebrickStrongholdMaxChunkDistance = 110
stonebrickStrongholdChainSpawnrate = 35

[RSStrongholdsConfig.nether]
netherStrongholdMaxChunkDistance = 85
addNetherStrongholdToModdedBiomes = true
netherStrongholdMinHeight = 10
netherStrongholdMaxHeight = 36
netherStrongholdChainSpawnrate = 50
[RSOutpostsConfig]
blacklistedOutpostBiomes = ""

[RSOutpostsConfig.outposts]
netherBrickOutpostMaxChunkDistance = 34
addNetherBrickOutpostToModdedBiomes = true
warpedOutpostMaxChunkDistance = 1001
addWarpedOutpostToModdedBiomes = false
crimsonOutpostMaxChunkDistance = 1001
addCrimsonOutpostToModdedBiomes = false
addOutpostBirchToModdedBiomes = true
outpostBirchMaxChunkDistance = 45
addOutpostJungleToModdedBiomes = true
outpostJungleMaxChunkDistance = 45
addOutpostGiantTreeTaigaToModdedBiomes = true
outpostGiantTreeTaigaMaxChunkDistance = 45
addOutpostDesertToModdedBiomes = true
outpostDesertMaxChunkDistance = 45
addOutpostBadlandsToModdedBiomes = true
outpostBadlandsMaxChunkDistance = 45
addOutpostSnowyToModdedBiomes = false
outpostSnowyMaxChunkDistance = 1001
addOutpostIcyToModdedBiomes = false
outpostIcyMaxChunkDistance = 1001
addOutpostTaigaToModdedBiomes = true
outpostTaigaMaxChunkDistance = 45
addOutpostOakToModdedBiomes = true
outpostOakMaxChunkDistance = 45
outpostEndMaxChunkDistance = 1001
addOutpostEndToModdedBiomes = false
[RSVillagesConfig]
addVillagesToModdedBiomes = false
blacklistedVillageBiomes = ""
badlandsVillageMaxChunkDistance = 30
birchVillageMaxChunkDistance = 38
darkForestVillageMaxChunkDistance = 38
jungleVillageMaxChunkDistance = 38
swampVillageMaxChunkDistance = 38
mountainsVillageMaxChunkDistance = 38
giantTaigaVillageMaxChunkDistance = 38
crimsonVillageMaxChunkDistance = 1001
warpedVillageMaxChunkDistance = 1001
villageOakMaxChunkDistance = 38
[RSWellsConfig]
addWellsToModdedBiomes = true
blacklistedWellBiomes = ""
canHaveBells = true

[RSWellsConfig.rarityPerChunk]
badlandsWellRarityPerChunk = 350
netherWellRarityPerChunk = 350
snowWellRarityPerChunk = 350
mossyStoneWellRarityPerChunk = 350
forestWellRarityPerChunk = 350
[RSShipwrecksConfig.blacklist]
blacklistedShipwreckBiomes = ""
addEndShipwreckToModdedBiomes = true
addNetherBricksShipwreckToModdedBiomes = false
addCrimsonShipwreckToModdedBiomes = false
addWarpedShipwreckToModdedBiomes = false
[RSShipwrecksConfig.maxChunkDistance]
endShipwreckMaxChunkDistance = 24
netherBricksShipwreckMaxChunkDistance = 1001
crimsonShipwreckMaxChunkDistance = 1001
warpedShipwreckMaxChunkDistance = 1001
[RSMansionsConfig.blacklist]
blacklistedMansionBiomes = ""
addMansionBirchToModdedBiomes = false
addMansionJungleToModdedBiomes = false
addMansionOakToModdedBiomes = false
addMansionSavannaToModdedBiomes = false
addMansionTaigaToModdedBiomes = false
addMansionDesertToModdedBiomes = false
addMansionSnowyToModdedBiomes = false
[RSMansionsConfig.maxChunkDistance]
mansionBirchMaxChunkDistance = 1001
mansionJungleMaxChunkDistance = 1001
mansionOakMaxChunkDistance = 1001
mansionSavannaMaxChunkDistance = 1001
mansionTaigaMaxChunkDistance = 1001
mansionDesertMaxChunkDistance = 1001
mansionSnowyMaxChunkDistance = 1001
[RSWitchHutsConfig.blacklist]
blacklistedWitchHutsBiomes = ""
addWitchHutsOakToModdedBiomes = false
addWitchHutsTaigaToModdedBiomes = false
addWitchHutsBirchToModdedBiomes = false
addWitchHutsDarkForestToModdedBiomes = false
addWitchHutsGiantTreeTaigaToModdedBiomes = false
[RSWitchHutsConfig.maxChunkDistance]
witchHutsOakMaxChunkDistance = 1001
witchHutsTaigaMaxChunkDistance = 1001
witchHutsBirchMaxChunkDistance = 1001
witchHutsDarkForestMaxChunkDistance = 101
witchHutsGiantTreeTaigaMaxChunkDistance = 1001
