[RSDungeonsConfig]
addDungeonsToModdedBiomes = true
blacklistedDungeonBiomes = ""

[RSDungeonsConfig.attemptsPerChunk]
badlandsDungeonAttemptsPerChunk = 5
darkForestDungeonAttemptsPerChunk = 5
desertDungeonAttemptsPerChunk = 5
jungleDungeonAttemptsPerChunk = 5
mushroomDungeonAttemptsPerChunk = 5
snowDungeonAttemptsPerChunk = 5
icyDungeonAttemptsPerChunk = 5
swampDungeonAttemptsPerChunk = 5
endDungeonAttemptsPerChunk = 0
netherDungeonAttemptsPerChunk = 0
oceanDungeonAttemptsPerChunk = 1

[RSDungeonsConfig.minHeight]
badlandsDungeonMinHeight = 2
darkForestDungeonMinHeight = 2
desertDungeonMinHeight = 2
jungleDungeonMinHeight = 2
mushroomDungeonMinHeight = 2
snowDungeonMinHeight = 2
icyDungeonMinHeight = 2
swampDungeonMinHeight = 2
endDungeonMinHeight = 2
netherDungeonMinHeight = 2
oceanDungeonMinHeight = 3

[RSDungeonsConfig.maxHeight]
badlandsDungeonMaxHeight = 255
darkForestDungeonMaxHeight = 255
desertDungeonMaxHeight = 255
jungleDungeonMaxHeight = 255
mushroomDungeonMaxHeight = 255
snowDungeonMaxHeight = 255
icyDungeonMaxHeight = 255
swampDungeonMaxHeight = 255
endDungeonMaxHeight = 255
netherDungeonMaxHeight = 255
oceanDungeonMaxHeight = 62
[RSMainConfig]
blacklistedDimensions = "the_bumblezone:the_bumblezone,the_aether:the_aether"
importModdedItems = true
blacklistedRSLoottablesFromImportingModdedItems = ""

[RSMainConfig.misc]
addBoulderToModdedBiomes = true
blacklistedBoulderBiomes = ""
boulderTiny = true
boulderGiant = true
diamondChanceInGiantBoulders = 7000
giantBouldersPerChunk = 0.25

[RSMainConfig.jungleFortress]
jungleFortressMaxChunkDistance = 80
addJungleFortressToModdedBiomes = true
blacklistedFortressBiomes = ""
silverfishSpawnrate = 0.5
lootChests = true

[RSMainConfig.igloos]
blacklistedIglooBiomes = ""
grassyIglooMaxChunkDistance = 40
addGrassyIglooToModdedBiomes = true
stoneIglooMaxChunkDistance = 40
addStoneIglooToModdedBiomes = true

[RSMainConfig.ruinedPortals]
blacklistedRuinedPortalsBiomes = ""
addRuinedPortalEndToModdedBiomes = false
ruinedPortalEndMaxChunkDistance = 1001

[RSMainConfig.ruins]
blacklistedRuinsBiomes = ""
addRuinsNetherToModdedBiomes = true
ruinsNetherMaxChunkDistance = 35

[RSMainConfig.cities]
blacklistedCitiesBiomes = ""
addCityNetherToModdedBiomes = false
cityNetherMaxChunkDistance = 1001
[RSTemplesConfig.temples]
blacklistedTempleBiomes = ""
netherWastelandTempleMaxChunkDistance = 30
addNetherWastelandTempleToModdedBiomes = false
netherBasaltTempleMaxChunkDistance = 30
addNetherBasaltTempleToModdedBiomes = false
netherCrimsonTempleMaxChunkDistance = 1001
addNetherCrimsonTempleToModdedBiomes = false
netherWarpedTempleMaxChunkDistance = 1001
addNetherWarpedTempleToModdedBiomes = false
netherSoulTempleMaxChunkDistance = 1001
addNetherSoulTempleToModdedBiomes = false
[RSTemplesConfig.pyramids]
blacklistedPyramidBiomes = ""
netherPyramidMaxChunkDistance = 1001
addNetherPyramidToModdedBiomes = false
badlandsPyramidMaxChunkDistance = 40
addBadlandsPyramidToModdedBiomes = true
pyramidSnowyMaxChunkDistance = 1001
addPyramidSnowyToModdedBiomes = false
pyramidEndMaxChunkDistance = 1001
addPyramidEndToModdedBiomes = false
pyramidIcyMaxChunkDistance = 1001
addPyramidIcyToModdedBiomes = false
[RSMineshaftsConfig]
lootChestsMS = true
addMineshaftsToModdedBiomes = true
blacklistedMineshaftBiomes = "betterend:sulphur_springs"

[RSMineshaftsConfig.spawnrate]
birchMineshaftSpawnrate = 50
jungleMineshaftSpawnrate = 50
desertMineshaftSpawnrate = 0
stoneMineshaftSpawnrate = 0
savannaMineshaftSpawnrate = 50
icyMineshaftSpawnrate = 0
oceanMineshaftSpawnrate = 0
taigaMineshaftSpawnrate = 40
swampAndDarkForestMineshaftSpawnrate = 50
endMineshaftSpawnrate = 0
netherMineshaftSpawnrate = 0
crimsonMineshaftSpawnrate = 0
warpedMineshaftSpawnrate = 0

[RSMineshaftsConfig.minHeight]
birchMineshaftMinHeight = 8
jungleMineshaftMinHeight = 8
desertMineshaftMinHeight = 8
stoneMineshaftMinHeight = 8
savannaMineshaftMinHeight = 8
icyMineshaftMinHeight = 8
oceanMineshaftMinHeight = 8
taigaMineshaftMinHeight = 8
swampAndDarkForestMineshaftMinHeight = 8
endMineshaftMinHeight = 30
netherMineshaftMinHeight = 8
crimsonMineshaftMinHeight = 8
warpedMineshaftMinHeight = 8

[RSMineshaftsConfig.maxHeight]
birchMineshaftMaxHeight = 45
jungleMineshaftMaxHeight = 45
desertMineshaftMaxHeight = 45
stoneMineshaftMaxHeight = 45
savannaMineshaftMaxHeight = 45
icyMineshaftMaxHeight = 45
oceanMineshaftMaxHeight = 25
taigaMineshaftMaxHeight = 45
swampAndDarkForestMineshaftMaxHeight = 45
endMineshaftMaxHeight = 37
netherMineshaftMaxHeight = 13
crimsonMineshaftMaxHeight = 13
warpedMineshaftMaxHeight = 13

[RSMineshaftsConfig.misc]
barrensIslandsEndMineshafts = false
[RSStrongholdsConfig]
strongholdSizeSH = 100.0
allowExtraSpawnersSH = false
lootChestsSH = true
turnOffVanillaStrongholds = false
blacklistedStrongholdBiomes = ""

[RSStrongholdsConfig.stonebrick]
allowStonebrickStrongholdToVanillaBiomes = false
addStonebrickStrongholdToModdedBiomes = false
silverfishSpawnrateSH = 0.8
stonebrickStrongholdMinHeight = 0
stonebrickStrongholdMaxHeight = 45
stonebrickStrongholdMaxChunkDistance = 110
stonebrickStrongholdChainSpawnrate = 35

[RSStrongholdsConfig.nether]
netherStrongholdMaxChunkDistance = 85
addNetherStrongholdToModdedBiomes = true
netherStrongholdMinHeight = 10
netherStrongholdMaxHeight = 36
netherStrongholdChainSpawnrate = 50
[RSOutpostsConfig]
blacklistedOutpostBiomes = ""

[RSOutpostsConfig.outposts]
netherBrickOutpostMaxChunkDistance = 1001
addNetherBrickOutpostToModdedBiomes = true
warpedOutpostMaxChunkDistance = 1001
addWarpedOutpostToModdedBiomes = false
crimsonOutpostMaxChunkDistance = 1001
addCrimsonOutpostToModdedBiomes = false
addOutpostBirchToModdedBiomes = true
outpostBirchMaxChunkDistance = 100
addOutpostJungleToModdedBiomes = true
outpostJungleMaxChunkDistance = 100
addOutpostGiantTreeTaigaToModdedBiomes = true
outpostGiantTreeTaigaMaxChunkDistance = 100
addOutpostDesertToModdedBiomes = true
outpostDesertMaxChunkDistance = 100
addOutpostBadlandsToModdedBiomes = true
outpostBadlandsMaxChunkDistance = 100
addOutpostSnowyToModdedBiomes = false
outpostSnowyMaxChunkDistance = 1001
addOutpostIcyToModdedBiomes = false
outpostIcyMaxChunkDistance = 1001
addOutpostTaigaToModdedBiomes = true
outpostTaigaMaxChunkDistance = 100
addOutpostOakToModdedBiomes = true
outpostOakMaxChunkDistance = 100
outpostEndMaxChunkDistance = 1001
addOutpostEndToModdedBiomes = false
[RSVillagesConfig]
addVillagesToModdedBiomes = false
blacklistedVillageBiomes = ""
badlandsVillageMaxChunkDistance = 70
birchVillageMaxChunkDistance = 70
darkForestVillageMaxChunkDistance = 70
jungleVillageMaxChunkDistance = 70
swampVillageMaxChunkDistance = 70
mountainsVillageMaxChunkDistance = 70
giantTaigaVillageMaxChunkDistance = 70
crimsonVillageMaxChunkDistance = 1001
warpedVillageMaxChunkDistance = 1001
villageOakMaxChunkDistance = 70
[RSWellsConfig]
addWellsToModdedBiomes = true
blacklistedWellBiomes = ""
canHaveBells = true

[RSWellsConfig.rarityPerChunk]
badlandsWellRarityPerChunk = 350
netherWellRarityPerChunk = 350
snowWellRarityPerChunk = 350
mossyStoneWellRarityPerChunk = 350
forestWellRarityPerChunk = 350
[RSShipwrecksConfig.blacklist]
blacklistedShipwreckBiomes = ""
addEndShipwreckToModdedBiomes = true
addNetherBricksShipwreckToModdedBiomes = false
addCrimsonShipwreckToModdedBiomes = false
addWarpedShipwreckToModdedBiomes = false
[RSShipwrecksConfig.maxChunkDistance]
endShipwreckMaxChunkDistance = 24
netherBricksShipwreckMaxChunkDistance = 1001
crimsonShipwreckMaxChunkDistance = 1001
warpedShipwreckMaxChunkDistance = 1001
[RSMansionsConfig.blacklist]
blacklistedMansionBiomes = ""
addMansionBirchToModdedBiomes = false
addMansionJungleToModdedBiomes = false
addMansionOakToModdedBiomes = false
addMansionSavannaToModdedBiomes = false
addMansionTaigaToModdedBiomes = false
addMansionDesertToModdedBiomes = false
addMansionSnowyToModdedBiomes = false
[RSMansionsConfig.maxChunkDistance]
mansionBirchMaxChunkDistance = 1001
mansionJungleMaxChunkDistance = 1001
mansionOakMaxChunkDistance = 1001
mansionSavannaMaxChunkDistance = 1001
mansionTaigaMaxChunkDistance = 1001
mansionDesertMaxChunkDistance = 1001
mansionSnowyMaxChunkDistance = 1001
[RSWitchHutsConfig.blacklist]
blacklistedWitchHutsBiomes = ""
addWitchHutsOakToModdedBiomes = false
addWitchHutsTaigaToModdedBiomes = false
addWitchHutsBirchToModdedBiomes = false
addWitchHutsDarkForestToModdedBiomes = false
addWitchHutsGiantTreeTaigaToModdedBiomes = false
[RSWitchHutsConfig.maxChunkDistance]
witchHutsOakMaxChunkDistance = 1001
witchHutsTaigaMaxChunkDistance = 1001
witchHutsBirchMaxChunkDistance = 1001
witchHutsDarkForestMaxChunkDistance = 101
witchHutsGiantTreeTaigaMaxChunkDistance = 1001
